apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management
spec:
  selector:
    matchLabels:
      app: employee-management
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: employee-management
    spec:
      containers:
        - name: employee-management
          image: it19148014/employeement-management-system:19bf6ceb62f65b1460bf239f5d53e3c3cc5b4185 #{{tag}}
          ports:
            - containerPort: 8089