apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customer-management
  name: customer-management
spec:
  ports:
    - protocol: TCP
      port: 8089
  selector:
    app: customer-management
  type: LoadBalancer