apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: employee-management
  name: employee-management
spec:
  ports:
    - protocol: TCP
      port: 8089
  selector:
    app: employee-management
  type: LoadBalancer