name: Docker Build Deploy



on:

  push:

    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1 # TODO: update to cluster name
  GKE_ZONE: us-central1 # TODO: update to cluster zone
  DEPLOYMENT_NAME: employee-management # TODO: update deployment name if changed in deployment.yaml

jobs:

  build:

    runs-on: ubuntu-latest

     # "id-token" with the intended permissions
    permissions:
      contents: "read"
      id-token: "write"


    steps:

      - uses: actions/checkout@v3

      - name: run shell script

        run: echo commit hash is ${{ github.sha }}

      - name: Login to Docker Hub

        uses: docker/login-action@v1

        with:

          username: ${{ secrets.DOCKER_USERNAME }}

          password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Build the Docker image

      #   run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}

      - name: Build and push

        uses: docker/build-push-action@v2

        with:

          context: .

          file: ./Dockerfile

          push: true

          tags: ${{ secrets.DOCKER_USERNAME }}/employee-management-system:${{ github.sha }}